# Generated by Django 4.0.5 on 2022-06-21 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cod_EIMES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Código EIMES', max_length=10)),
                ('tipo', models.CharField(choices=[('E', 'Eléctrico'), ('I', 'Instrumentación'), ('M', 'Mecánico'), ('O', 'Otro')], default='E', help_text='Tipo de Equipo EIMES', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre Modelo', max_length=100)),
                ('descripcion_modelo', models.TextField(help_text='Descripción del Equipo', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre Marca', max_length=50)),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CAT.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_equipo', models.TextField(help_text='Descripción del Equipo', max_length=1000)),
                ('cod_EIMES', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='CAT.cod_eimes')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='CAT.marca')),
            ],
        ),
    ]
