# Generated by Django 4.0.5 on 2022-06-21 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CAT', '0002_remove_marca_modelo_equipo_modelo_modelo_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[(1, 'Vigente'), (0, 'Vencido')], max_length=1)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('archivo', models.FileField(upload_to='')),
                ('proveedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_EIMES', models.CharField(max_length=11, null=True, unique=True)),
                ('cod_QR', models.CharField(max_length=50, unique=True)),
                ('serie', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('e', 'Eléctrico'), ('i', 'Instrumentación'), ('m', 'Mecánico'), ('o', 'Otros')], help_text='Categoría del Equipos', max_length=1)),
                ('descripcion_corta', models.CharField(max_length=50)),
                ('descripcion_larga', models.CharField(max_length=1000)),
                ('nro_maletas', models.IntegerField()),
                ('proveedor', models.CharField(max_length=50)),
                ('certif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CAT.certificado')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='cod_EIMES',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='modelo',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='descripcion_modelo',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='modelo',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='manual',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='CAT.marca'),
        ),
        migrations.DeleteModel(
            name='Cod_EIMES',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.AddField(
            model_name='equipo_instance',
            name='modelo',
            field=models.ForeignKey(help_text='Representación Equipo Real', on_delete=django.db.models.deletion.RESTRICT, to='CAT.modelo'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CAT.equipo_instance'),
        ),
    ]
