# Generated by Django 4.0.5 on 2022-06-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAT', '0003_certificado_equipo_instance_remove_equipo_cod_eimes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo_instance',
            name='certif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CAT.certificado'),
        ),
        migrations.AlterField(
            model_name='equipo_instance',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo_instance',
            name='descripcion_larga',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
