# Generated by Django 4.0.5 on 2022-06-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAT', '0005_alter_equipo_instance_nro_maletas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='fecha_fin',
            field=models.DateField(blank=True),
        ),
    ]
