# Generated by Django 4.0.5 on 2022-06-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAT', '0006_alter_certificado_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Vigente'), (0, 'Vencido')]),
        ),
    ]
