# Generated by Django 4.0.5 on 2022-06-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAT', '0007_alter_certificado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
